/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.net.URL;
import java.net.URLConnection;
import java.sql.*;
import javax.swing.*;

//Class for adding new Medical Records of the patient to the database
public class AddNewMedicalRecord extends javax.swing.JFrame {

    /**
     * Creates new form AddNewMedicalRecord
     */
    private Connection con = null;
    private PreparedStatement pst = null;
    String filePath = null;
    String fileName = null;

    //setting up constructor
    public AddNewMedicalRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDisease = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTest = new javax.swing.JTextArea();
        Save = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jAttach = new javax.swing.JButton();
        jPath = new javax.swing.JTextField();
        jImageLabel = new javax.swing.JLabel();
        clearFieldsButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("RELATED DISEASE:");

        jDisease.setColumns(20);
        jDisease.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jDisease.setLineWrap(true);
        jDisease.setRows(5);
        jScrollPane1.setViewportView(jDisease);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("TEST TYPE:");

        jTest.setColumns(20);
        jTest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTest.setLineWrap(true);
        jTest.setRows(5);
        jScrollPane2.setViewportView(jTest);

        Save.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Save.setText("Save");
        Save.setPreferredSize(new java.awt.Dimension(79, 31));
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Cancel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.setPreferredSize(new java.awt.Dimension(79, 31));
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        jAttach.setText("Browse");
        jAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAttachActionPerformed(evt);
            }
        });

        jPath.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jPath.setText("File path to be shown...");

        clearFieldsButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        clearFieldsButton.setText("Clear");
        clearFieldsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFieldsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jImageLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(clearFieldsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPath)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jAttach)
                                .addGap(2, 2, 2))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jAttach))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearFieldsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jImageLabel)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Adding the user's entery for new medical records to the database by save button
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        try {
            con = DatabaseConnection.ConnectDB();

            String sql = "INSERT INTO MedicalRecords (PatientID,Disease,TestType,FileLocation) VALUES(?,?,?,?)";
            pst = con.prepareStatement(sql);
            pst.setInt(1, SearchPatientMenu.currentPatient.getID());
            pst.setString(2, jDisease.getText());
            pst.setString(3, jTest.getText());
            pst.setString(4, fileName);
            pst.executeUpdate();
            con.close();

            uploadFile();

            JOptionPane.showMessageDialog(this, "Saved it successfully", "Record", JOptionPane.INFORMATION_MESSAGE);

        } //handling exceptions
        catch (Exception e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
        }
    }//GEN-LAST:event_SaveActionPerformed

    //returning to previous menue with none or no further data to add to the database by cancel button
    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        this.hide();
    }//GEN-LAST:event_CancelActionPerformed

    //Attaching the image related to patinet's medical records which will be uploaded to the database
    private void jAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAttachActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        filePath = file.getAbsolutePath();
        jPath.setText(filePath);
        fileName = file.getName();
    }//GEN-LAST:event_jAttachActionPerformed

    //clearing text fields
    private void clearFieldsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFieldsButtonActionPerformed
        jDisease.setText("");
        jTest.setText("");
        jPath.setText("");
    }//GEN-LAST:event_clearFieldsButtonActionPerformed

    private void uploadFile() {
        final int BUFFER_SIZE = 4096;
        String ftpUrl = "ftp://%s:%s@%s/%s;type=i";
        String host = "f14-preview.royalwebhosting.net";
        String user = "2018995";
        String pass = "docson0000";

        ftpUrl = String.format(ftpUrl, user, pass, host, "/" + fileName);

        try {
            URL url = new URL(ftpUrl);
            URLConnection conn = url.openConnection();
            OutputStream outputStream = conn.getOutputStream();
            FileInputStream inputStream = new FileInputStream(filePath);

            byte[] buffer = new byte[BUFFER_SIZE];
            int bytesRead = -1;
            while ((bytesRead = inputStream.read(buffer)) != -1) {
                outputStream.write(buffer, 0, bytesRead);
            }

            inputStream.close();
            outputStream.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    //running the applet in the main method
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewMedicalRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Save;
    private javax.swing.JButton clearFieldsButton;
    private javax.swing.JButton jAttach;
    private javax.swing.JTextArea jDisease;
    private javax.swing.JLabel jImageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jPath;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTest;
    // End of variables declaration//GEN-END:variables

}
