
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author mert.donmezyurek-ug
 */
public class DoctorMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form DoctorMainMenu and doesn't allow the user to create new
     * user if it is doctor account.
     */
    public DoctorMainMenu() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        if (Login.currentUser.getExpertise().equals("Doctor")) {
            CreateNewAccountButton.setVisible(false);
        }
        doctorNameText.setText("Dr. " + Login.currentUser.getName() + " " + Login.currentUser.getSurname());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchPatientButton = new javax.swing.JButton();
        AddPatientButton = new javax.swing.JButton();
        CreateNewAccountButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        doctorNameText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 620));

        SearchPatientButton.setFont(new java.awt.Font("Century Gothic", 0, 25)); // NOI18N
        SearchPatientButton.setText("Search Patient");
        SearchPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPatientButtonActionPerformed(evt);
            }
        });

        AddPatientButton.setFont(new java.awt.Font("Century Gothic", 0, 25)); // NOI18N
        AddPatientButton.setText("Add Patient");
        AddPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPatientButtonActionPerformed(evt);
            }
        });

        CreateNewAccountButton.setFont(new java.awt.Font("Century Gothic", 0, 25)); // NOI18N
        CreateNewAccountButton.setText("Create New Account");
        CreateNewAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewAccountButtonActionPerformed(evt);
            }
        });

        LogOutButton.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        LogOutButton.setText("Log Out");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        doctorNameText.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        doctorNameText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doctorNameText.setText("Doctor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(250, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CreateNewAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(LogOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(250, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doctorNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(LogOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(doctorNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(SearchPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CreateNewAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        Login frm = new Login();
        frm.setVisible(true);//making the LogOut button visible
        frm.setLocation(getLocation()); //Gets the location of the current window and then sets it to the next opening window
        frm.setSize(getSize());//Gets the size of the current window and then sets it to the next opening window
        frm.setExtendedState(getExtendedState());//Controls whether it is full screen or not and then according to that opens the next window in full screen or not
        this.hide(); //Hides the current window while screening the next window
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void CreateNewAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewAccountButtonActionPerformed
        AddNewAccountMenu frm = new AddNewAccountMenu();
        frm.setVisible(true);//making the create new account button visible
        frm.setLocation(getLocation());//Gets the location of the current window and then sets it to the next opening window
        frm.setSize(getSize());//Gets the size of the current window and then sets it to the next opening window
        frm.setExtendedState(getExtendedState());//Controls whether it is full screen or not and then according to that opens the next window in full screen or not
        this.hide();//Hides the current window while screening the next window
    }//GEN-LAST:event_CreateNewAccountButtonActionPerformed

    private void AddPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPatientButtonActionPerformed

        AddNewPatientMenu frm = new AddNewPatientMenu();
        frm.setVisible(true);//making the create new account button visible
        frm.setLocation(getLocation());//Gets the location of the current window and then sets it to the next opening window
        frm.setSize(getSize());//Gets the size of the current window and then sets it to the next opening window
        frm.setExtendedState(getExtendedState());//Controls whether it is full screen or not and then according to that opens the next window in full screen or not
        this.hide();//Hides the current window while screening the next window

    }//GEN-LAST:event_AddPatientButtonActionPerformed

    private void SearchPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPatientButtonActionPerformed
        SearchPatientMenu frm = new SearchPatientMenu();
        frm.setVisible(true);//making the create new account button visible
        frm.setLocation(getLocation());//Gets the location of the current window and then sets it to the next opening window
        frm.setSize(getSize());//Gets the size of the current window and then sets it to the next opening window
        frm.setExtendedState(getExtendedState());//Controls whether it is full screen or not and then according to that opens the next window in full screen or not
        this.hide();//Hides the current window while screening the next window

    }//GEN-LAST:event_SearchPatientButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        new DoctorMainMenu().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPatientButton;
    private javax.swing.JButton CreateNewAccountButton;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton SearchPatientButton;
    private javax.swing.JLabel doctorNameText;
    // End of variables declaration//GEN-END:variables
}
