
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class SearchPatientMenu extends javax.swing.JFrame {

    /**
     * Creates new form SearchPatientWindow
     */
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    static Patient currentPatient = new Patient();

    public SearchPatientMenu() {

        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.WHITE);
        setInvisibleComponentsInBluePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        Space = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        BlueBackgroundPanel = new javax.swing.JPanel();
        PatientInfoButton = new javax.swing.JButton();
        DiagnosesButton = new javax.swing.JButton();
        RecordsButton = new javax.swing.JButton();
        OperationsButton = new javax.swing.JButton();
        VisitsButton = new javax.swing.JButton();
        MainPane = new javax.swing.JTabbedPane();
        ScrollPane = new javax.swing.JScrollPane();
        DiagnosesTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        Back.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        Back.setText("Back");
        Back.setToolTipText("");
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Space.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Space.setText("Enter patient ID number");
        Space.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SpaceMouseClicked(evt);
            }
        });
        Space.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpaceActionPerformed(evt);
            }
        });
        Space.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SpaceKeyPressed(evt);
            }
        });

        Search.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        Search.setText("Search");
        Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        BlueBackgroundPanel.setBackground(new java.awt.Color(51, 153, 255));

        PatientInfoButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        PatientInfoButton.setText("Patient Info");
        PatientInfoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PatientInfoButton.setFocusCycleRoot(true);
        PatientInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientInfoButtonActionPerformed(evt);
            }
        });

        DiagnosesButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        DiagnosesButton.setText("Diagnoses");
        DiagnosesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DiagnosesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiagnosesButtonActionPerformed(evt);
            }
        });

        RecordsButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        RecordsButton.setText("Records");
        RecordsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordsButtonActionPerformed(evt);
            }
        });

        OperationsButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        OperationsButton.setText("Operations");
        OperationsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OperationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperationsButtonActionPerformed(evt);
            }
        });

        VisitsButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        VisitsButton.setText("Visits");
        VisitsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VisitsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitsButtonActionPerformed(evt);
            }
        });

        MainPane.setBackground(new java.awt.Color(255, 255, 255));
        MainPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        MainPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MainPane.setName(""); // NOI18N

        ScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        ScrollPane.setBorder(null);

        DiagnosesTable.setAutoCreateRowSorter(true);
        DiagnosesTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DiagnosesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                " ", " "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DiagnosesTable.setMaximumSize(new java.awt.Dimension(2147483647, 101010225));
        DiagnosesTable.setMinimumSize(new java.awt.Dimension(30, 64));
        DiagnosesTable.setName(""); // NOI18N
        DiagnosesTable.setPreferredSize(new java.awt.Dimension(150, 225));
        DiagnosesTable.setRowHeight(25);
        DiagnosesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiagnosesTableMouseClicked(evt);
            }
        });
        ScrollPane.setViewportView(DiagnosesTable);
        if (DiagnosesTable.getColumnModel().getColumnCount() > 0) {
            DiagnosesTable.getColumnModel().getColumn(0).setResizable(false);
            DiagnosesTable.getColumnModel().getColumn(0).setHeaderValue(" ");
            DiagnosesTable.getColumnModel().getColumn(1).setResizable(false);
            DiagnosesTable.getColumnModel().getColumn(1).setHeaderValue(" ");
        }

        MainPane.addTab("Diagnoses", ScrollPane);

        addButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add_icon.png"))); // NOI18N
        addButton.setText("Add Button");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BlueBackgroundPanelLayout = new javax.swing.GroupLayout(BlueBackgroundPanel);
        BlueBackgroundPanel.setLayout(BlueBackgroundPanelLayout);
        BlueBackgroundPanelLayout.setHorizontalGroup(
            BlueBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlueBackgroundPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(BlueBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VisitsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RecordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OperationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DiagnosesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(BlueBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BlueBackgroundPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(MainPane)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlueBackgroundPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(235, Short.MAX_VALUE))))
        );

        BlueBackgroundPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {DiagnosesButton, OperationsButton, PatientInfoButton, RecordsButton, VisitsButton});

        BlueBackgroundPanelLayout.setVerticalGroup(
            BlueBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlueBackgroundPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(BlueBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BlueBackgroundPanelLayout.createSequentialGroup()
                        .addComponent(PatientInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(DiagnosesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(RecordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(OperationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(VisitsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BlueBackgroundPanelLayout.createSequentialGroup()
                        .addComponent(MainPane, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );

        BlueBackgroundPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {DiagnosesButton, OperationsButton, PatientInfoButton, RecordsButton, VisitsButton});

        MainPane.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(Space, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addComponent(BlueBackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Space, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(BlueBackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        DoctorMainMenu frm = new DoctorMainMenu();
        frm.setVisible(true);
        frm.setLocation(getLocation());
        frm.setSize(getSize());
        frm.setExtendedState(getExtendedState());
        this.hide();
    }//GEN-LAST:event_BackActionPerformed

    private void SpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpaceActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        try {
            String sql = "SELECT * FROM Patients WHERE ID= '" + Space.getText() + "'";
            connectAndExecute(sql);

            if (rs.next()) {
                setCurrentPatient(rs);

                setVisibleComponentsInBluePanel();

                //Create Patient Information
                createPatientInformationTable();

            } else {
                JOptionPane.showMessageDialog(this, "There is no such patient in the system. Please try again!", "Error", JOptionPane.ERROR_MESSAGE);
                setInvisibleComponentsInBluePanel();
            }

        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }


    }//GEN-LAST:event_SearchActionPerformed

    private void PatientInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientInfoButtonActionPerformed
        // TODO add your handling code here:
        try {
            createPatientInformationTable();
            addButton.setVisible(false);
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_PatientInfoButtonActionPerformed

    private void VisitsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitsButtonActionPerformed

        try {
            String sql = "SELECT DoctorName AS 'Doctor Name',Date AS 'Date',DoctorInfo AS 'Doctor Information' FROM Visits WHERE PatientID= '" + currentPatient.getID() + "'";
            connectAndExecute(sql);
            createTable("Visits", "Add Visit", rs);
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_VisitsButtonActionPerformed

    private void RecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordsButtonActionPerformed

        try {
            String sql = "SELECT Disease AS 'Disease',Date AS 'Date',TestType AS 'Test Type', FileLocation AS 'File' FROM MedicalRecords WHERE PatientID= '" + currentPatient.getID() + "'";
            connectAndExecute(sql);
            createTable("Records", "Add Record", rs);
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_RecordsButtonActionPerformed

    private void OperationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperationsButtonActionPerformed

        try {
            String sql = "SELECT OperatedArea AS 'Operated Area',Date AS 'Date',Report AS 'Report' FROM Operations WHERE PatientID= '" + currentPatient.getID() + "'";
            connectAndExecute(sql);
            createTable("Operations", "Add Operation", rs);
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_OperationsButtonActionPerformed

    private void DiagnosesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiagnosesButtonActionPerformed
        // TODO add your handling code here:

        try {
            String sql = "SELECT Illness AS 'Illness',Date AS 'Date',Description AS 'Description' FROM Diagnoses WHERE PatientID= '" + currentPatient.getID() + "'";
            connectAndExecute(sql);
            createTable("Diagnoses", "Add Diagnosis", rs);
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DiagnosesButtonActionPerformed

    private void SpaceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SpaceKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {

                String sql = "SELECT * FROM Patients WHERE ID= '" + Space.getText() + "'";
                connectAndExecute(sql);

                if (rs.next()) {
                    setCurrentPatient(rs);

                    setVisibleComponentsInBluePanel();

                    //Create Patient Information
                    createPatientInformationTable();
                    /////////
                    DiagnosesTable.requestDefaultFocus();
                    con.close();
                } else {
                    JOptionPane.showMessageDialog(this, "There is no such patient in the system. Please try again!", "Error", JOptionPane.ERROR_MESSAGE);
                    setInvisibleComponentsInBluePanel();
                }
            } catch (HeadlessException | SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_SpaceKeyPressed

    private void SpaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpaceMouseClicked
        // TODO add your handling code here:
        Space.setText("");

    }//GEN-LAST:event_SpaceMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (addButton.getText().equals("Add Diagnosis")) {
            AddNewDiagnosisMenu frm = new AddNewDiagnosisMenu();
            frm.setVisible(true);
            frm.setLocationRelativeTo(getContentPane());
        }

        if (addButton.getText().equals("Add Record")) {
            AddNewMedicalRecord frm = new AddNewMedicalRecord();
            frm.setVisible(true);
            frm.setLocationRelativeTo(getContentPane());
        }

        if (addButton.getText().equals("Add Operation")) {
            AddNewOperation frm = new AddNewOperation();
            frm.setVisible(true);
            frm.setLocationRelativeTo(getContentPane());
        }

        if (addButton.getText().equals("Add Visit")) {
            AddNewVisit frm = new AddNewVisit();
            frm.setVisible(true);
            frm.setLocationRelativeTo(getContentPane());
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void DiagnosesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiagnosesTableMouseClicked
        if (addButton.getText().equals("Add Record")) {
            int index = DiagnosesTable.convertRowIndexToModel(DiagnosesTable.rowAtPoint(evt.getPoint()));
            if (index >= 0) {
                if (evt.getClickCount() == 2) {
                    try {
                        String URL = "ftp://2018995:docson0000@f14-preview.royalwebhosting.net/" + DiagnosesTable.getModel().getValueAt(index, 3);
                        java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e.getMessage());
                    }
                }
            }

        }
    }//GEN-LAST:event_DiagnosesTableMouseClicked

    private void setVisibleComponentsInBluePanel() {
        PatientInfoButton.setVisible(true);
        DiagnosesButton.setVisible(true);
        RecordsButton.setVisible(true);
        OperationsButton.setVisible(true);
        VisitsButton.setVisible(true);
        MainPane.setVisible(true);
        addButton.setVisible(false); //when re-searching, hide the add button
    }

    private void setInvisibleComponentsInBluePanel() {
        PatientInfoButton.setVisible(false);
        DiagnosesButton.setVisible(false);
        RecordsButton.setVisible(false);
        OperationsButton.setVisible(false);
        VisitsButton.setVisible(false);
        MainPane.setVisible(false);
        addButton.setVisible(false);
    }

    private void createPatientInformationTable() {
        MainPane.removeAll();
        MainPane.addTab("Patient Information", ScrollPane);
        DiagnosesTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {"ID", currentPatient.getID()},
                    {"Name", currentPatient.getName()},
                    {"Surname", currentPatient.getSurname()},
                    {"Birth Date", currentPatient.getBirthDate()},
                    {"Gender", currentPatient.getGender()},
                    {"Blood Type", currentPatient.getBloodType()},
                    {"Address", currentPatient.getAddress()},
                    {"Phone Number", currentPatient.getPhoneNumber()},
                    {"Registeration Date", currentPatient.getRegistrationDate()}
                },
                new String[]{
                    " ", " "
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        DiagnosesTable.setPreferredSize(new java.awt.Dimension(150, (DiagnosesTable.getRowCount()) * DiagnosesTable.getRowHeight()));
    }

    private void setCurrentPatient(ResultSet rs) throws SQLException {
        currentPatient.setID(rs.getInt("ID"));
        currentPatient.setName(rs.getString("Name"));
        currentPatient.setSurname(rs.getString("Surname"));
        currentPatient.setGender(rs.getString("Gender"));
        currentPatient.setBirthDate((rs.getDate("BirthDate")).toString());
        currentPatient.setRegistrationDate(rs.getString("RegistrationDate"));
        currentPatient.setBloodType(rs.getString("BloodType"));
        currentPatient.setPhoneNumber(rs.getString("PhoneNumber"));
        currentPatient.setAddress(rs.getString("Address"));
    }

    private void createTable(String tableName, String buttonText, ResultSet rs) {
        MainPane.removeAll();
        MainPane.addTab(tableName, ScrollPane);
        DiagnosesTable.setModel(DbUtils.resultSetToTableModel(rs));
        DiagnosesTable.setPreferredSize(new java.awt.Dimension(150, (DiagnosesTable.getRowCount()) * DiagnosesTable.getRowHeight()));

        for (int c = 0; c < DiagnosesTable.getColumnCount(); c++) {
            Class<?> col_class = DiagnosesTable.getColumnClass(c);
            DiagnosesTable.setDefaultEditor(col_class, null);        // remove editor
        }
        addButton.setVisible(true);
        addButton.setText(buttonText);
    }

    private void connectAndExecute(String res) throws SQLException {
        con = DatabaseConnection.ConnectDB();
        pst = con.prepareStatement(res);
        rs = pst.executeQuery();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        (new SearchPatientMenu()).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JPanel BlueBackgroundPanel;
    private javax.swing.JButton DiagnosesButton;
    private javax.swing.JTable DiagnosesTable;
    private javax.swing.JTabbedPane MainPane;
    private javax.swing.JButton OperationsButton;
    private javax.swing.JButton PatientInfoButton;
    private javax.swing.JButton RecordsButton;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton Search;
    private javax.swing.JTextField Space;
    private javax.swing.JButton VisitsButton;
    private javax.swing.JButton addButton;
    // End of variables declaration//GEN-END:variables
}
